kind = "web"
previewPath = "/"
title = "Nisha Godani"
version = "1.0.0"
id = "artifacts/nisha-godani"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22828

[services.development]
run = "pnpm --filter @workspace/nisha-godani run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nisha-godani", "run", "build" ]
serve = "static"
publicDir = "artifacts/nisha-godani/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22828"
BASE_PATH = "/"
